version: '3'

services:
      backend:
        env_file:
            "./server/.env"
        build:
            context: "./server"
            dockerfile: "./Dockerfile"
        image: "prev_on_back"
        ports: 
          - "8000:8000"
      frontend:
        env_file:
            "./client/.env"
        build:
            context: "./client"
            dockerfile: "./Dockerfile"
        image: "prev_on_front"
        ports:
          - "3000:3000"
        links:
          - "backend:be"